### ISSUE TITLE
Java 7u51 installer complains that Java 8 is already installed

### ISSUE THREAD

**Issue by jbcpollak** [boxen/puppet-java#34]
I have manually installed Java 8. When I run Boxen, I get this error message:

> Error: Execution of '/usr/sbin/installer -pkg /private/tmp/dmg.h7gWu3/Java 7 Update 51.pkg -target /' returned 1: installer: Error - You are trying to install Java 7 Update 51, however Java 8 is already installed.
> Visit java.com/newerversionexists for more information.

> Error: /Stage[main]/Java::V7u51/Java::Version[v7u51]/Java[7u51]/Package[jre-7u51.dmg]/ensure: change from absent to present failed: Execution of '/usr/sbin/installer -pkg /private/tmp/dmg.h7gWu3/Java 7 Update 51.pkg -target /' returned 1: installer:  Error - You are trying to install Java 7 Update 51, however Java 8 is already installed.
Visit java.com/newerversionexists for more information.

I would like to support having both versions installed at the same time.

I looked into command line parameters for the installer, but could not find anything relevant. Strangely, if I run the same command manually on the command line, Java installs without an error, but if I run it from Puppet, I get the above errors.

**Comment by mikemcquaid** [comment]
Fixed by #54.
