### ISSUE TITLE
JRE/JDK packages fail to install on Yosemite

### ISSUE THREAD

**Issue by dgoodlad** [boxen/puppet-java#45]
The official JRE and JDK packages fail to install on Yosemite. Their install scripts contain a poorly-written version check, which compares OS X versions as strings. Since `"10.10"`, when compared as a string, is less than `"10.7.3"`, the packages refuse to install.

This can be resolved in one of a few ways:

1. Modify the version check in `Distribution` file in the two `.pkg`s and distribute modified `.dmg`s
2. Wait for Oracle to update their official releases
3. Split up the JDK/JRE installs, and use [Apple's Java distribution](http://support.apple.com/kb/DL1572) to get at least the JRE installed

**Comment by mikemcquaid** [comment]
Fixed by #49.
