### ISSUE TITLE
(Yosemite 10.10) Boxen fails to install Java with puppet-java 1.8.0

### ISSUE THREAD

**Issue by ktec** [boxen/puppet-java#53]
Get the following error:

Could not retrieve fact='java_version', resolution='<anonymous>': undefined method `gsub' for nil:NilClass

It works when I specify version 1.0.6, haven't tried all the versions in between yet, will let you know..

**Comment by ktec** [comment]
Ok, just checked with 1.7.1 and seems to be ok..

**Comment by mikemcquaid** [comment]
What's your puppet version?

**Comment by petems** [comment]
@ktec @mikemcquaid Yeah, that was a bug with the original fact, it should be fixed in a later version of the module (> 1.7.0 I think) :+1:

**Comment by ktec** [comment]
Well yes its fixed in 1.7.0, but NOT fixed in the latest 1.8.0 tag.

**Comment by nmteck** [comment]
Also experiencing and can verify this issue occurs with the 1.8.0 tag and not with 1.7.0

**Comment by mikemcquaid** [comment]
Can you provide some more information about your system e.g. whether Java is installed, what version and where? Thanks!

**Comment by julienlavergne** [comment]
Please close this topic. Brew is the on ly useful tool.

Envoyé de mon iPhone

**Comment by ccelebi** [comment]
Also having the same issue with the 1.8.3 tag. Java is not installed on mine either.

**Comment by julienlavergne** [comment]
Please go to homebrew

Envoyé de mon iPhone

**Comment by mikemcquaid** [comment]
@julienlavergne Stop commenting on this issue or you will be blocked on the Boxen organisation.

**Comment by julienlavergne** [comment]
Puppet Java is unused. Please prefer brew cask. Its just an advice.

Envoyé de mon iPhone

**Comment by mikemcquaid** [comment]
@julienlavergne I'm a Homebrew maintainer. Please do not post any more "advice" on this issue or you will be blocked on the Boxen organisation.

**Comment by julienlavergne** [comment]
Ok Mike

Envoyé de mon iPhone

**Comment by MikeMcQuaid** [comment]
Should be fixed in 1.8.4.
